### ISSUE TITLE
Hide native extra UI

### ISSUE THREAD

**Issue by strarsis** [wakirin/Litepicker#82]
**Is your feature request related to a problem? Please describe.**
Currently, the browser native UI is still shown for the `input` `date` element, even with Litepicker loaded. 
(Accidentally) selecting the native UI elements results in the Litepicker and the native browser calendar being shown simultaneously.

**Describe the solution you'd like**
Hide the browser native extra UI for date input fields (should be possible with some CSS).

**Describe alternatives you've considered**
Add the necessary CSS by myself, this also includes toggling a class on the `input` when Litepicker has been initialized on them.

```scss
@mixin hide-date-input-extra-ui {
  &::-webkit-outer-spin-button, // spinner (1)
  &::-webkit-inner-spin-button, // spinner (2)
  &::-moz-outer-spin-button, // spinner (1)
  &::-moz-inner-spin-button, // spinner (2)
  &::-webkit-calendar-picker-indicator, // drop-down button
  &::-webkit-clear-button, // clear button
  &::-ms-clear { // clear button (IE)
    display: none;
    -webkit-appearance: none;
    margin: 0;
  }

  &::-webkit-input-placeholder {
    visibility: hidden !important;
  }
}
````

**Additional context**
https://stackoverflow.com/questions/17954966/how-to-get-rid-of-x-and-up-down-arrow-elements-of-a-input-date
https://css-tricks.com/snippets/css/turn-off-number-input-spinners/
